name: computing-in-context
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - spyder
  - notebook
  - pyzmq
  - jupyter
  - plotly
  - jupyter-book
  - statsmodels
  - openpyxl
  - codecov
-pip:
  - sphinx-rtd-theme